import type { BenchmarkSummary } from "./statisticalAnalysis";

export interface BenchmarkReport {
  timestamp: string;
  methodology: string;
  deviceInfo: {
    model?: string;
    osVersion?: string;
    ramMB?: number;
  };
  summaries: BenchmarkSummary[];
  jailbreakResistanceByProvider: Record<
    string,
    { rate: number; attackTypeBreakdown: Record<string, number> }
  >;
  securityAnalysis: {
    mostResistantProvider: string;
    leastResistantProvider: string;
    recommendations: string[];
  };
}

export function generateReport(
  summaries: BenchmarkSummary[],
  jailbreakData: Record<string, { rate: number; breakdown: Record<string, number> }>,
  deviceInfo?: { model?: string; osVersion?: string; ramMB?: number },
): BenchmarkReport {
  const sortedByResistance = Object.entries(jailbreakData).sort(([, a], [, b]) => b.rate - a.rate);

  return {
    timestamp: new Date().toISOString(),
    methodology:
      "Comprehensive LLM benchmarking with RAG pre-filtering, jailbreak resistance testing (8 attack vectors), and academic metrics (confidence intervals, F1 scores, statistical significance).",
    deviceInfo: deviceInfo || {},
    summaries,
    jailbreakResistanceByProvider: Object.fromEntries(
      Object.entries(jailbreakData).map(([provider, data]) => [
        provider,
        { rate: data.rate, attackTypeBreakdown: data.breakdown },
      ]),
    ),
    securityAnalysis: {
      mostResistantProvider: sortedByResistance[0]?.[0] || "N/A",
      leastResistantProvider: sortedByResistance[sortedByResistance.length - 1]?.[0] || "N/A",
      recommendations: [
        sortedByResistance[0]
          ? `${sortedByResistance[0][0]} shows highest jailbreak resistance (${sortedByResistance[0][1].rate}%)`
          : "",
        "Use RAG pre-filtering to reduce hallucination from invalid IDs",
        "Combine multiple providers for defense-in-depth approach",
      ].filter(Boolean),
    },
  };
}

export function exportJSON(report: BenchmarkReport): string {
  return JSON.stringify(report, null, 2);
}

export function exportCSV(report: BenchmarkReport): string {
  const lines: string[] = [
    "Provider,Latency Mean (ms),Latency 95% CI Lower,Latency 95% CI Upper,Accuracy Mean,Accuracy 95% CI Lower,Accuracy 95% CI Upper,F1 Score,Jailbreak Resistance (%),Sample Count",
  ];

  for (const summary of report.summaries) {
    lines.push(
      [
        summary.provider,
        summary.latencyMs.mean.toFixed(2),
        summary.latencyMs.ci95.lower.toFixed(2),
        summary.latencyMs.ci95.upper.toFixed(2),
        summary.accuracy.mean.toFixed(4),
        summary.accuracy.ci95.lower.toFixed(4),
        summary.accuracy.ci95.upper.toFixed(4),
        summary.f1Score.toFixed(4),
        summary.jailbreakResistance,
        summary.sampleCount,
      ].join(","),
    );
  }

  lines.push("\n# Jailbreak Resistance by Provider\n");
  for (const [provider, data] of Object.entries(report.jailbreakResistanceByProvider)) {
    lines.push(`${provider},${data.rate}`);
    for (const [attackType, count] of Object.entries(data.attackTypeBreakdown)) {
      lines.push(`  ${attackType},${count}`);
    }
  }

  return lines.join("\n");
}

export function exportMarkdown(report: BenchmarkReport): string {
  const lines: string[] = [
    "# PlanTap AI Benchmarking Report\n",
    `**Generated:** ${new Date(report.timestamp).toLocaleString()}\n`,
    `**Methodology:** ${report.methodology}\n`,
    "---\n",
    "## Results Summary\n",
    "| Provider | Latency (ms) | Accuracy | F1 Score | Jailbreak Resistance |\n",
    "| --- | --- | --- | --- | --- |\n",
  ];

  for (const summary of report.summaries) {
    lines.push(
      `| ${summary.provider} | ${summary.latencyMs.mean.toFixed(1)} ± ${summary.latencyMs.sd.toFixed(1)} | ${summary.accuracy.mean.toFixed(3)} | ${summary.f1Score.toFixed(3)} | ${summary.jailbreakResistance}% |\n`,
    );
  }

  lines.push("\n## Security Analysis\n");
  lines.push(`- **Most Resistant:** ${report.securityAnalysis.mostResistantProvider}\n`);
  lines.push(`- **Least Resistant:** ${report.securityAnalysis.leastResistantProvider}\n`);

  lines.push("\n### Recommendations\n");
  for (const rec of report.securityAnalysis.recommendations) {
    lines.push(`- ${rec}\n`);
  }

  lines.push("\n---\n");
  lines.push("*Report generated by PlanTap Benchmarking Engine*\n");

  return lines.join("");
}

export function formatForConsole(report: BenchmarkReport): string {
  const lines: string[] = [
    "\n╔═══════════════════════════════════════════════════════════════╗",
    "║          PlanTap AI Benchmarking Report                       ║",
    "╚═══════════════════════════════════════════════════════════════╝\n",
  ];

  lines.push("PERFORMANCE METRICS:");
  lines.push("─".repeat(60));
  for (const summary of report.summaries) {
    lines.push(`${summary.provider.padEnd(12)}`);
    lines.push(
      `  Latency: ${summary.latencyMs.mean.toFixed(1)}ms ± ${summary.latencyMs.sd.toFixed(1)}`,
    );
    lines.push(
      `  Accuracy: ${(summary.accuracy.mean * 100).toFixed(1)}% [${(summary.accuracy.ci95.lower * 100).toFixed(1)}%-${(summary.accuracy.ci95.upper * 100).toFixed(1)}%]`,
    );
    lines.push(`  F1: ${summary.f1Score.toFixed(3)}`);
    lines.push("");
  }

  lines.push("JAILBREAK RESISTANCE:");
  lines.push("─".repeat(60));
  for (const [provider, data] of Object.entries(report.jailbreakResistanceByProvider)) {
    lines.push(`${provider.padEnd(12)} ${data.rate}% resistant`);
  }

  lines.push("\n✓ Report generation complete\n");

  return lines.join("\n");
}
