// This file exists to keep the Convex TypeScript project non-empty.
//
// When there are no user-defined Convex functions yet, TypeScript reports
// TS18003 ("No inputs were found") because `convex/tsconfig.json` excludes the
// autogenerated files in `convex/_generated`.

export {};
